project:
  type: website

website:
  title: "greta blog"
  navbar:
    right:
      - icon: chat-fill
        href: https://forum.greta-stats.org/
      - icon: github
        href: https://github.com/greta-dev
      - icon: twitter
        href: https://twitter.com/greta_stats
format:
  html:
    theme: [yeti, styles.scss]



